services:
  pipedal:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - ./build/src/pipedald
      - /etc/pipedal/config
      - ./vite/dist
      - -port
      - "0.0.0.0:8080"
      - -log-level
      - debug
    ports:
      - "8080:8080"
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    restart: unless-stopped
