services:
  pipedal:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:8080"
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /sys/devices/system/cpu:/sys/devices/system/cpu
    group_add:
      - audio
    cap_add:
      - SYS_NICE
      - IPC_LOCK
    ulimits:
      rtprio: 95
      nice:
        soft: 29
        hard: 29
    restart: unless-stopped
